version: '3'
services:
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.5.0
    container_name: opensearch-dashboards-only
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["<domain_endpoint_url>"]'
      OPENSEARCH_USERNAME: '<user_name>'
      OPENSEARCH_PASSWORD: '<pass_word>'
    networks:
      - opensearch-net
networks:
  opensearch-net:
