version: '3'
services:
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.5.0
    container_name: opensearch-dashboards-ssl
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["<domain_endpoint_url>"]'
      OPENSEARCH_USERNAME: '<user_name>'
      OPENSEARCH_PASSWORD: '<pass_word>'
      OPENSEARCH_SSL_VERIFICATIONMODE: certificate # none, certificate, full
      OPENSEARCH_SSL_CERTIFICATEAUTHORITIES: '["certs/<CA_certificate>","/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"]' # local CA, root certs
      SERVER_SSL_ENABLED: 'true'
      SERVER_SSL_CERTIFICATE: 'certs/<node_certificate>'
      SERVER_SSL_KEY: 'certs/<node_certificate_key>'
      OPENSEARCH_SECURITY_COOKIE_SECURE: 'true'
    networks:
      - opensearch-net
    volumes:
      - <path_to_folder_w_certs_keys>:/certs
networks:
  opensearch-net:
