version: '3'
services:
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.5.0
    container_name: opensearch-dashboards-only
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["<domain_endpoint_url>"]'
      OPENSEARCH_USERNAME: '<user_name>'
      OPENSEARCH_PASSWORD: '<pass_word>'
      OPENSEARCH_SSL_VERIFICATIONMODE: certificate # none, certificate, full
      OPENSEARCH_SSL_CERTIFICATEAUTHORITIES: '["<full_path_to_CA_certificates>"]'
      SERVER_SSL_ENABLED: 'true'
      SERVER_SSL_CERTIFICATE: '<full_path_to_client_certificate>'
      SERVER_SSL_KEY: '<full_path_client_certificate_key>'
      OPENSEARCH_SECURITY_COOKIE_SECURE: 'true'
    networks:
      - opensearch-net
networks:
  opensearch-net:
